config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  get 'notifications/link_through'

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'posts#index'

  resources :posts do
    resources :comments
    member do
      get 'like'      
      get 'unlike'      
    end
  end
  
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'browse', to: 'posts#browse', as: :browse_posts
  
  post ':user_name/follow_user',   to: 'relationships#follow_user',   as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get   ':user_name',      to: 'profiles#show',   as: :profile
  get   ':user_name/edit', to: 'profiles#edit',   as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user  = User.find_by user_name: params[:user_name]
    @posts = User.find_by(user_name: params[:user_name])
      .posts.order created_at: :desc
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update profile_params
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path @user.user_name
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  private
    def profile_params
      params.require(:user).permit(:avatar, :bio)
    end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = form_for @user, url: {action: "update"}, html: { multipart: true } do |f|
          .row
            .col-md-12
              .form-group.text-center
                %h4 Change your profile image:
                .img-circle
                  = profile_avatar_select(@user)
                = f.file_field :avatar, onChange: 'loadFile(event)'
          .row
            .col-md-12
              .form-group.text-center
                %h4 Update your bio:
                = f.text_area :bio, label: false, rows: 4, style: 'width: 100%'
                .form-group.text-center
                  = f.submit "Update Profile", class: 'btn btn-success'

app/views/profiles/show.html.haml
.posts-wrapper
  .row.profile-header
    .col-md-6
      .img-circle
        = profile_avatar_select(@user)

    .col-md-6
      .user-name-and-follow
        %h3.profile-user-name
          = @user.user_name
        %span
          - if @user == current_user
            = link_to 'Edit Your Profile', edit_profile_path(@user.user_name), class: 'btn edit-button'
          - else
            - if current_user.is_following? @user
              = link_to 'Following', unfollow_user_path,
                                    remote: true,
                                    class: 'btn unfollow-button',
                                    id: 'unfollow-button',
                                    method: :post
            - else
              = link_to 'Follow', follow_user_path,
                                  remote: true,
                                  class: 'btn follow-button',
                                  id: 'follow-button',
                                  method: :post

      %p.profile-bio
        = @user.bio
      .user-statistics
        %p
          = pluralize @user.posts.count, 'post'

- @posts.each do |post|
  = render 'posts/post', post: post