config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  get 'notifications/link_through'

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'posts#index'

  resources :posts do
    resources :comments
    member do
      get 'like'      
      get 'unlike'      
    end
  end
  
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'browse', to: 'posts#browse', as: :browse_posts
  
  post ':user_name/follow_user',   to: 'relationships#follow_user',   as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get   ':user_name',      to: 'profiles#show',   as: :profile
  get   ':user_name/edit', to: 'profiles#edit',   as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true

  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:index,:create, :destroy]
  before_action :set_comment, only: [:destroy]

  def index
    @comments = @post.comments.order("created_at ASC")

    respond_to do |format|
      format.html { render layout: !request.xhr? }
    end
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      create_notification @post
      respond_to do |format|
        format.html { redirect_to :back }
        format.js 
      end
    else
      flash[:alert] = "Check the comment form, something went horribly wrong."
      render root_path
    end

  end

  def destroy
    if current_user.owns_comment? @comment
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to :back }
        format.js 
      end
    end
  end

  private
    def create_notification post
      return if post.user.id == current_user.id
      Notification.create(user_id: post.user.id,
        notified_by_id: current_user.id,
        post_id: post.id,
        notice_type: 'comment')
    end

    def comment_params
      params.require(:comment).permit(:content)
    end

    def set_post
      @post = Post.find params[:post_id]
    end

    def set_comment
      @comment = @post.comments.find params[:id]
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
#comment
  .user-name
    = link_to comment.user.user_name, profile_path(comment.user.user_name)
  .comment-content
    = comment.content
  - if current_user.owns_comment? comment
    = link_to post_comment_path(post, comment), remote: true, method: :delete,data: { confirm: "Are you sure?" } do
      %span(class="glyphicon glyphicon-remove delete-comment")

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>')
  .append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>')
  .html("<%= j render @post.comments, post: @post, comment: @comment %>");

app/views/comments/index.html.haml
= render @comments, post: @post