config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  get 'notifications/link_through'

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'posts#index'

  resources :posts do
    resources :comments
    member do
      get 'like'      
      get 'unlike'      
    end
  end
  
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'browse', to: 'posts#browse', as: :browse_posts
  
  post ':user_name/follow_user',   to: 'relationships#follow_user',   as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get   ':user_name',      to: 'profiles#show',   as: :profile
  get   ':user_name/edit', to: 'profiles#edit',   as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

end

app/models/post.rb
class Post < ActiveRecord::Base
  # Validations
  validates :image,   presence: true
  validates :caption, presence: true, length: { minimum: 4, maximum: 300 }
  validates :user_id, presence: true
  has_attached_file :image, styles: { :medium => "640x" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  #Relationships
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  
  # For Liking Posts
  acts_as_votable

  # Scopes
  scope :of_followed_users, -> (following_users) { where user_id: following_users }
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only:[:show, :edit, :update, :destroy, :like, :unlike]
  before_action :owned_post, only:[:edit, :update, :destroy]
  before_action :authenticate_user!

  def  browse
    @posts = Post.all.order(created_at: :desc).page params[:page]
    respond_to do |format|
      format.html
      format.js 
    end
  end

  def index
    @posts = Post.of_followed_users(current_user.following).order(created_at: :desc).page params[:page]
    respond_to do |format|
      format.html
      format.js 
    end
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build post_params

    if @post.save
      flash[:success] = "Your post has been created!"
      redirect_to posts_path
    else
      flash.now[:alert] = "Your new post couldn't be created!. Please check the form."
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update post_params
      flash[:success] = "Post updated."
      redirect_to posts_path
    else
      flash.now[:alert] = "Update failed. Please check the form."
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url
  end

  def like
    if @post.liked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def unlike
    if @post.unliked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  private
    def post_params
      params.require(:post).permit(:image, :caption)
    end

    def set_post
     @post = Post.find params[:id]
    end

    def owned_post
      unless current_user.owns_post? @post
        flash[:alert] = "You does not have permissions to be there."
        redirect_to root_path
      end
    end

end

app/helpers/posts_helper.rb
module PostsHelper  

  def display_likes post
    votes = post.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 2
    count_likers(votes)
  end

  def liked_post post
    if current_user.voted_for? post
      render 'posts/unlike_button', post: post
    else
      render 'posts/like_button', post: post
    end
  end

  private
    def list_likers votes
      user_names = []
      unless votes.blank?
        votes.voters.each do |voter|
          user_names.push(link_to voter.user_name,
                                  profile_path(voter.user_name),
                                  class: 'user-name')
        end
        user_names.to_sentence.html_safe + like_plural(votes)
      end
    end

    def count_likers votes
      vote_count = votes.size
      vote_count.to_s + ' likes'
    end

    def like_plural votes
      return ' like this' if votes.count > 1
      ' likes this'
    end
end

app/views/posts/_form.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = form_image_select @post
        = simple_form_for @post, html: { multipart: true } do |f|

          .row
            .col-md-12.text-center
              = f.error_notification

          .container-fluid
            .form-group.text-center
              %h4 Upload an image (this is required):
              = f.input :image, label: false, input_html: { onChange: 'loadFile(event)' }
            .form-group.text-center
              = f.input :caption, label: false, placeholder: 'Add your caption', input_html: { class: 'form-control' } 
            .form-group.text-center
              = f.button :submit, class: 'btn-success btn-block'

app/views/posts/_like_button.html.haml
= link_to '', like_post_path(post.id), 
            remote: true, 
            id: "like_#{post.id}",
            class: "like glyphicon glyphicon-heart-empty"

app/views/posts/_likes.html.haml
.likes{id: "likes_#{post.id}"}
  = display_likes post

app/views/posts/_post.html.haml
.posts-wrapper
  .post
    .post-head
      .user-name
        = link_to post.user.user_name, profile_path(post.user.user_name)
      .time-ago
        = time_ago_in_words post.created_at
    .image.center-block
      = link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post)

    .post-bottom
      = render 'posts/likes', post: post 
      .caption
    
        .caption-content
          .user-name
            = link_to post.user.user_name, profile_path(post.user.user_name)
          = post.caption

        .comments{id: "comments_#{post.id}"}
          - if post.comments.any?
            .paginator{id: "#comments-paginator-#{post.id}"}
              - unless post.comments.count <= 4
                = link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', data: { post_id: "#{post.id}", type: "html" }
            = render post.comments.last(4), post: post
    
    .comment-like-form.row
      .like-button.col-sm-1
        = liked_post post
      .comment-form.col-sm-11
        = form_for [post, post.comments.build], remote: true do |f|
          = f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}"

app/views/posts/_post_dashboard.html.haml
#posts
  = render 'posts'

#paginator.text-center
  = link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more'

app/views/posts/_post_dashboard.js.erb
$('#posts')
  .append("<%= escape_javascript(render 'posts')%>");

$('#paginator')
  .html("<%=escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");

if (!$('#load_more').length) { 
  $('#paginator').remove(); 
}

app/views/posts/_unlike_button.html.haml
= link_to '', unlike_post_path(post.id), 
            remote: true, 
            id: "unlike_#{post.id}",
            class: "like glyphicon glyphicon-heart"

app/views/posts/browse.html.haml
= render 'post_dashboard', posts: @posts

app/views/posts/edit.html.haml
= render 'form'

.text-center.edit-links
  = link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }
  |
  = link_to "Back", posts_path

app/views/posts/index.html.haml
#posts
  = render 'posts'

#paginator.text-center
  = link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more'

app/views/posts/like.js.erb
var unlikeButton =  $("#like_<%= @post.id %>")
var parent = unlikeButton.parent();

// Remove unlike Button
unlikeButton.remove();

// Add Like Button
parent.append("<%= j (render partial: 'posts/unlike_button', locals: { post: @post} ) %>")

// Render Likes
$("#likes_<%= @post.id %>")
  .html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
= render 'post', post: @post

- if current_user.owns_post? @post
  .text-center.edit-links
    = link_to "Cancel", posts_path
    |
    = link_to "Edit Post", edit_post_path(@post)
- else
  .text-center.edit-links
    =link_to "Cancel", posts_path

app/views/posts/unlike.js.erb
var likeButton =  $("#unlike_<%= @post.id %>")
var parent = likeButton.parent();

// Remove unlike Button
likeButton.remove();

// Add Like Button
parent.append("<%= j (render partial: 'posts/like_button', locals: { post: @post} ) %>")

// Render Likes
$("#likes_<%= @post.id %>")
  .html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");